// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: petstore.proto

package petstore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN   Status = 0
	Status_AVAILABLE Status = 1
	Status_PENDING   Status = 2
	Status_SOLD      Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "AVAILABLE",
		2: "PENDING",
		3: "SOLD",
	}
	Status_value = map[string]int32{
		"UNKNOWN":   0,
		"AVAILABLE": 1,
		"PENDING":   2,
		"SOLD":      3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_petstore_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_petstore_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_petstore_proto_rawDescGZIP(), []int{0}
}

type Pet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=petstore.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pet) Reset() {
	*x = Pet{}
	mi := &file_petstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_petstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_petstore_proto_rawDescGZIP(), []int{0}
}

func (x *Pet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pet) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

type Pets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pets          []*Pet                 `protobuf:"bytes,1,rep,name=pets,proto3" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pets) Reset() {
	*x = Pets{}
	mi := &file_petstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pets) ProtoMessage() {}

func (x *Pets) ProtoReflect() protoreflect.Message {
	mi := &file_petstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pets.ProtoReflect.Descriptor instead.
func (*Pets) Descriptor() ([]byte, []int) {
	return file_petstore_proto_rawDescGZIP(), []int{1}
}

func (x *Pets) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

var File_petstore_proto protoreflect.FileDescriptor

const file_petstore_proto_rawDesc = "" +
	"\n" +
	"\x0epetstore.proto\x12\bpetstore\x1a\x1bgoogle/protobuf/empty.proto\"S\n" +
	"\x03Pet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.petstore.StatusR\x06status\")\n" +
	"\x04Pets\x12!\n" +
	"\x04pets\x18\x01 \x03(\v2\r.petstore.PetR\x04pets*;\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tAVAILABLE\x10\x01\x12\v\n" +
	"\aPENDING\x10\x02\x12\b\n" +
	"\x04SOLD\x10\x032\xf8\x01\n" +
	"\bPetStore\x122\n" +
	"\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x0e.petstore.Pets\"\x00\x12(\n" +
	"\x06GetPet\x12\r.petstore.Pet\x1a\r.petstore.Pet\"\x00\x12+\n" +
	"\tCreatePet\x12\r.petstore.Pet\x1a\r.petstore.Pet\"\x00\x12+\n" +
	"\tUpdatePet\x12\r.petstore.Pet\x1a\r.petstore.Pet\"\x00\x124\n" +
	"\tDeletePet\x12\r.petstore.Pet\x1a\x16.google.protobuf.Empty\"\x00B\fZ\n" +
	"./petstoreb\x06proto3"

var (
	file_petstore_proto_rawDescOnce sync.Once
	file_petstore_proto_rawDescData []byte
)

func file_petstore_proto_rawDescGZIP() []byte {
	file_petstore_proto_rawDescOnce.Do(func() {
		file_petstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_petstore_proto_rawDesc), len(file_petstore_proto_rawDesc)))
	})
	return file_petstore_proto_rawDescData
}

var file_petstore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_petstore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_petstore_proto_goTypes = []any{
	(Status)(0),           // 0: petstore.Status
	(*Pet)(nil),           // 1: petstore.Pet
	(*Pets)(nil),          // 2: petstore.Pets
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_petstore_proto_depIdxs = []int32{
	0, // 0: petstore.Pet.status:type_name -> petstore.Status
	1, // 1: petstore.Pets.pets:type_name -> petstore.Pet
	3, // 2: petstore.PetStore.GetAll:input_type -> google.protobuf.Empty
	1, // 3: petstore.PetStore.GetPet:input_type -> petstore.Pet
	1, // 4: petstore.PetStore.CreatePet:input_type -> petstore.Pet
	1, // 5: petstore.PetStore.UpdatePet:input_type -> petstore.Pet
	1, // 6: petstore.PetStore.DeletePet:input_type -> petstore.Pet
	2, // 7: petstore.PetStore.GetAll:output_type -> petstore.Pets
	1, // 8: petstore.PetStore.GetPet:output_type -> petstore.Pet
	1, // 9: petstore.PetStore.CreatePet:output_type -> petstore.Pet
	1, // 10: petstore.PetStore.UpdatePet:output_type -> petstore.Pet
	3, // 11: petstore.PetStore.DeletePet:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_petstore_proto_init() }
func file_petstore_proto_init() {
	if File_petstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_petstore_proto_rawDesc), len(file_petstore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_petstore_proto_goTypes,
		DependencyIndexes: file_petstore_proto_depIdxs,
		EnumInfos:         file_petstore_proto_enumTypes,
		MessageInfos:      file_petstore_proto_msgTypes,
	}.Build()
	File_petstore_proto = out.File
	file_petstore_proto_goTypes = nil
	file_petstore_proto_depIdxs = nil
}
